# server
host: 127.0.0.1
port: 3000

# 
# afterCreatedToStartServer: true

# only for SPA
favicon: 

# an array of string
vendor: ['react', 'react-dom', 'react-router-dom', 'react-router-redux', 'redux', 'redux-thunk', 'history']

# tell webpack which extensions to auto search when it resolves modules. With this,
# you'll be able to do `require('./utils')` instead of `require('./utils.js')`
extensions: ['.js', '.jsx', '.vue', '.css', '.scss', '.less']

# detial: to webpack website
# {}
provide:
  React: react

# https://webpack.js.org/configuration/externals/
# object || array || string
externals: []

# for development. // inline-source-map
devtool: eval-source-map

# default size is 5k
# less or equal base64_image_limit value use data url else use img url with hash hash
base64_image_limit: 5120

module_noParse: []

# {object}
resolve_alias:
  pages: pages
  components: components
  utils: utils
  assets: assets
  app: app

# CDN domain, or just leave it blank
static:
  # here use relative path
  start: /
  test: /
  # here use CDN domain
  pre: /
  #here use CDN domain
  release: /

# HTTP
# you can set api server address for development: //test.example.api.com (to replace your server address)
# {object}
# configure global variables
globals:
  API_HTTPS:
    start: //
    test: //
    pre: //
    release: //

  API_HTTP:
    start: //
    test:  //
    pre:  //
    release: //
  # ...to parse more one
  #OTHER_API_HTTP:
    #start: //
    #...

# directory for production
build_dir: dist

# default structure for application and develement
#
dev_structure_dir:
  # webpack and development entry dir
  base: src
  
  # type of string or object. if the value is string means it is SPA app, otherwise is multiple app.
  # following code is multiple app config.
  # pages:
  #  - home
  #  - about
  pages: pages
  
  # for global management common static assets, likes css, image, font and et.
  assets: assets
  
  components: components

  utils: utils

  # for store common data for react application.
  # do not change the values of 'app'
  # This data will be removed in the future as it only exists for temp.
  app:
    base: app

    actions: actions

    action_type: constants

    reducers: reducers

    selectors: selectors

    store: store
